package co.edu.usergioarboleda.inventario.app.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author JuanDiego-Arenas
 */
public class FrmInventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public FrmInventario() {
        initComponents();
        this.setVisible(true);
    }

    public void Limpiar(){
        TxtNombreProducto.setText("");
        TxtPrecioProducto.setText("");
        TxtInventarioProducto.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LblBienvenida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LblNombreProducto = new javax.swing.JLabel();
        LblPrecioProducto = new javax.swing.JLabel();
        LblInventarioProducto = new javax.swing.JLabel();
        TxtNombreProducto = new javax.swing.JTextField();
        TxtPrecioProducto = new javax.swing.JTextField();
        TxtInventarioProducto = new javax.swing.JTextField();
        BtnAgregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblInventario = new javax.swing.JTable();
        BtnBorrarProducto = new javax.swing.JButton();
        BtnActualizarProducto = new javax.swing.JButton();
        BtnInforme = new javax.swing.JButton();
        BtnRefrescar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto5: Inventario Productos");

        LblBienvenida.setText("¡Bienvenido a la APP de inventario!");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Nuevo Producto"));

        LblNombreProducto.setText("Nombre");

        LblPrecioProducto.setText("Precio");

        LblInventarioProducto.setText("Inventario");

        BtnAgregarProducto.setText("Agregar Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LblPrecioProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LblInventarioProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnAgregarProducto)
                                .addComponent(TxtInventarioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblNombreProducto)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombreProducto)
                    .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrecioProducto)
                    .addComponent(TxtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblInventarioProducto)
                    .addComponent(TxtInventarioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarProducto)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblInventario);

        BtnBorrarProducto.setText("Borrar Producto");

        BtnActualizarProducto.setText("Actualizar Producto");

        BtnInforme.setText("Informes");

        BtnRefrescar.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(BtnBorrarProducto)
                .addGap(39, 39, 39)
                .addComponent(BtnActualizarProducto)
                .addGap(43, 43, 43)
                .addComponent(BtnInforme)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LblBienvenida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRefrescar)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblBienvenida)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBorrarProducto)
                    .addComponent(BtnActualizarProducto)
                    .addComponent(BtnInforme))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarProducto;
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JButton BtnBorrarProducto;
    private javax.swing.JButton BtnInforme;
    private javax.swing.JButton BtnRefrescar;
    private javax.swing.JLabel LblBienvenida;
    private javax.swing.JLabel LblInventarioProducto;
    private javax.swing.JLabel LblNombreProducto;
    private javax.swing.JLabel LblPrecioProducto;
    private javax.swing.JTable TblInventario;
    private javax.swing.JTextField TxtInventarioProducto;
    private javax.swing.JTextField TxtNombreProducto;
    private javax.swing.JTextField TxtPrecioProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizarProducto() {
        return BtnActualizarProducto;
    }

    public void setBtnActualizarProducto(JButton BtnActualizarProducto) {
        this.BtnActualizarProducto = BtnActualizarProducto;
    }

    public JButton getBtnAgregarProducto() {
        return BtnAgregarProducto;
    }

    public void setBtnAgregarProducto(JButton BtnAgregarProducto) {
        this.BtnAgregarProducto = BtnAgregarProducto;
    }

    public JButton getBtnBorrarProducto() {
        return BtnBorrarProducto;
    }

    public void setBtnBorrarProducto(JButton BtnBorrarProducto) {
        this.BtnBorrarProducto = BtnBorrarProducto;
    }

    public JButton getBtnInforme() {
        return BtnInforme;
    }

    public void setBtnInforme(JButton BtnInforme) {
        this.BtnInforme = BtnInforme;
    }

    public JTable getTblInventario() {
        return TblInventario;
    }

    public void setTblInventario(JTable TblInventario) {
        this.TblInventario = TblInventario;
    }

    public JTextField getTxtInventarioProducto() {
        return TxtInventarioProducto;
    }

    public void setTxtInventarioProducto(JTextField TxtInventarioProducto) {
        this.TxtInventarioProducto = TxtInventarioProducto;
    }

    public JTextField getTxtNombreProducto() {
        return TxtNombreProducto;
    }

    public void setTxtNombreProducto(JTextField TxtNombreProducto) {
        this.TxtNombreProducto = TxtNombreProducto;
    }

    public JTextField getTxtPrecioProducto() {
        return TxtPrecioProducto;
    }

    public void setTxtPrecioProducto(JTextField TxtPrecioProducto) {
        this.TxtPrecioProducto = TxtPrecioProducto;
    }

    public JButton getBtnRefrescar() {
        return BtnRefrescar;
    }

    public void setBtnRefrescar(JButton BtnRefrescar) {
        this.BtnRefrescar = BtnRefrescar;
    }

}
